---

- name: Check if we have required variables
  assert:
    that:
        - grf_api_prometheus_user is defined
        - grf_api_key is defined

- include_vars: "{{ item }}"
  with_first_found:
    - default.yml

- name: Download Agent file
  get_url:
    url: "{{ grf_agent_release_url }}"
    dest: "/tmp/agent-linux.zip"
    mode: '0644'

- name: Install unzip
  package:
    name: unzip
    state: present

- name: Unarchive Agent
  unarchive:
    src: "/tmp/agent-linux.zip"
    dest: "{{ grf_agent_location }}"
    remote_src: yes
    mode: '0755'

- name: Create directory for Agent's config file
  file:
    state: directory
    recurse: yes
    path: "{{ grf_config_location }}"
    mode: 0755

- name: Create Agent's config file
  template:
    src: "{{ grf_agent_config_template }}"
    dest: "{{ grf_config_location }}/agent-config.yaml"
    mode: 0644
    force: yes

- name: Ensure Grafana Agent Service
  include_role:
    name: systemd-service
  vars:
    systemd_service: "{{ _grf_agent_systemd }}"

- name: Install Promtail
  include_tasks: "promtail.yml"
  when:
    - loki_user is defined
