---

- name: Check if we have required variables
  assert:
    that:
        - grf_api_loki_user is defined
        - grf_api_key is defined

- name: Download latest Promtail release
  get_url:
    url: "{{ grf_promtail_release_url }}"
    dest: "/tmp/promtail-linux.zip"
    mode: '0644'

- name: Create directory for Promtail's files
  file:
    state: directory
    recurse: yes
    path: "{{ grf_promtail_location }}"
    mode: 0755

- name: Unarchive Promtail
  unarchive:
    src: "/tmp/promtail-linux.zip"
    dest: "{{ grf_promtail_location }}"
    remote_src: yes
    mode: '0755'

- name: Create an Promtail config file
  template:
    src: "{{ grafana_promtail_config_template }}"
    dest: "{{ grf_promtail_location }}/promtail-config.yaml"
    mode: 0644
    force: yes

- name: Ensure Grafana Agent Service
  include_role:
    name: systemd-service
  vars:
    systemd_service: "{{ _promtail_agent_systemd }}"
